version: '3.8'
services:
  clickhouse:
    image: yandex/clickhouse-server
    container_name: clickhouse
    ports:
      - "8123:8123"
  vector:
    image: segateekb/vector_eventlog:latest
    volumes:
      - ./config:/etc/vector
      - ./logs:/var/log/eventlog/
    environment:
      BASE_LIST: |
        databases:
          - 1c_baseName: "1C_CRM"
            ch_baseName: "1C_CRM_ch"
          - 1c_baseName: "erp26"
            ch_baseName: "erp26_ch"
      CH_USER: "default"
      CH_PASSWORD: ""
    depends_on:
      - clickhouse  

