version: '3.8'
services:
  clickhouse:
    image: yandex/clickhouse-server
    container_name: clickhouse
    ports:
      - "8123:8123"
  vector:
    image: segateekb/vector_eventlog:latest
    volumes:
      - ./config:/etc/vector
      - ./logs:/var/log/eventlog/
      - ./examples/baseList.yaml:/etc/vector/baseList.yaml #Местоположение файла "По умолчанию" в таком случае переменную окружения BASE_LIST__FILE можно не указывать
    environment:
      CH_USER: "default"
      CH_PASSWORD: ""
    depends_on:
      - clickhouse  

